server:
  port: 8888 #端口号
  servlet:
    context-path: '/sweet' #项目访问路径

spring:
  datasource: #数据源
    url: mysql://localhost:3306/xiangqin?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123@qwe
  jackson:
    date-format: 'yyyy-MM-dd' #格式化json

  resources: # 静态资源路径
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/

  thymeleaf:
    cache: false  # 使用模板缓存
    suffix: .html
    encoding: UTF-8
    prefix: classpath:/templates/
    mode: HTML5