server:
  port: 8888 #端口号
  servlet:
    context-path: '/sweet' #项目访问路径

spring:
  datasource: #数据源
    url: jdbc:mysql://localhost:3306/xiangqin?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123@qwe
  jackson:
    date-format: 'yyyy-MM-dd' #格式化json

  resources: # 静态资源路径
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/,classpath:/css/,classpath:/css1/,classpath:/fonts/,classpath:/fonts1/,classpath:/images/,classpath:/images1/,classpath:/js/,classpath:/js1/,classpath:/plugins/,classpath:/styles/

  thymeleaf:
    cache: false  # 使用模板缓存
    suffix: .html
    encoding: UTF-8
    prefix: classpath:/templates/
    mode: HTML5